Para simular um contexto real de engenharia de dados aplicado ao futebol, foi desenvolvido um processo ETL (Extract, Transform, Load), responsável pela extração, transformação e carregamento dos dados para uma base de dados PostgreSQL. Esta abordagem permite estruturar os dados de forma consistente e persistente, facilitando posteriormente a sua exploração analítica e integração em aplicações e dashboards.

O processo ETL é iniciado na etapa de extração dos dados da StatsBomb através da respetiva API. Todo o código desta fase foi desenvolvido de forma modular e parametrizável, permitindo que a integração de novas competições possa ser realizada de forma simples, escalável e com alterações mínimas ao pipeline existente.

# Extract

In [9]:
# import das bibliotecas necessárias
import pandas as pd
import numpy as np
from statsbombpy import sb
import warnings
from tqdm import tqdm
warnings.filterwarnings("ignore")

In [10]:
# função para obter competições
def get_competitions(competition_season_pairs):
    comps_df = sb.competitions()

    mask = False

    for competition_name, season_name in competition_season_pairs:
        mask |= (
            (comps_df["competition_name"] == competition_name) &
            (comps_df["season_name"] == season_name)
        )

    return comps_df[mask]

Devido às limitações de disponibilidade dos dados open data da StatsBomb, que incluem poucas competições completas com dados recentes, foi selecionado o Euro 2024. Esta competição apresenta uma cobertura completa e atual, tornando-se adequada para a aplicação e avaliação da métrica desenvolvida.

In [11]:
competitions = [
    #("1. Bundesliga", "2023/2024"),
    ("UEFA Euro", "2024")
]

competitions_df = get_competitions(competitions)

# guardar os dados raw das competições
competitions_df.to_parquet("../data/raw/competitions.parquet", index=False)
competitions_df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
73,55,282,Europe,UEFA Euro,male,False,True,2024,2026-05-01T19:54:25.846072,2026-05-01T19:58:06.077979,2026-05-01T19:58:06.077979,2026-05-01T19:54:25.846072

In [12]:
matches_dfs = []

# iterar sobre as competições e obter os jogos
for _, row in competitions_df.iterrows():
    matches = sb.matches(

        # adicionar colunas de competition_id e season_id para ligação entre tabelas
        competition_id=row["competition_id"],
        season_id=row["season_id"]
    )

    matches_dfs.append(matches)

matches_df = pd.concat(matches_dfs, ignore_index=True)

#guardar os dados raw dos jogos
matches_df.to_parquet("../data/raw/matches.parquet", index=False)
matches_df

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3930166,2024-06-18,19:00:00.000,2,1,available,available,2026-05-01T19:52:36.631184,2026-05-01T19:56:35.877702,1,...,Spain,1000468,Ivan Hašek,None,1963-09-06,60,Czech Republic,1.1.0,2,2
1,3930159,2024-06-15,13:00:00.000,1,3,available,available,2026-05-01T19:45:59.392947,2026-05-01T19:50:52.970161,1,...,Italy,2832,Murat Yakin,None,1974-09-15,221,Switzerland,1.1.0,2,2
2,3930163,2024-06-16,19:00:00.000,0,1,available,available,2026-05-01T19:48:19.783129,2026-05-01T19:49:47.226912,1,...,Serbia,277,Gareth Southgate,None,1970-09-03,68,England,1.1.0,2,2
3,3930181,2024-06-25,19:00:00.000,0,0,available,available,2026-05-01T19:48:27.887397,2026-05-01T19:50:03.279607,3,...,England,1733,Matjaž Kek,None,1961-09-09,208,Slovenia,1.1.0,2,2
4,3930178,2024-06-24,19:00:00.000,1,1,available,available,2026-05-01T19:45:23.956799,2026-05-01T19:46:35.413328,3,...,Croatia,399,Luciano Spalletti,None,1959-03-07,112,Italy,1.1.0,2,2
5,3930160,2024-06-15,16:00:00.000,3,0,available,available,2026-05-01T19:45:01.052020,2026-05-01T19:46:14.941863,1,...,Spain,307,Zlatko Dalić,None,1966-10-26,56,Croatia,1.1.0,2,2
6,3930170,2024-06-20,13:00:00.000,1,1,available,available,2026-05-01T19:50:11.398180,2026-05-01T19:56:14.983173,2,...,Slovenia,5908,Dragan Stojković,None,1965-03-03,203,Serbia,1.1.0,2,2
7,3938643,2024-06-25,16:00:00.000,1,1,available,available,2026-05-01T09:32:36.453598,2026-05-01T09:37:02.207863,3,...,France,363,Michał Probierz,None,1972-09-24,182,Poland,1.1.0,2,2
8,3938641,2024-06-21,16:00:00.000,1,3,available,available,2026-05-01T09:29:24.560133,2026-05-01T09:30:43.170204,2,...,Poland,380,Ralf Rangnick,None,1958-06-29,85,Germany,1.1.0,2,2
9,3938642,2024-06-22,13:00:00.000,1,1,available,available,2026-05-01T09:31:28.135473,2026-05-01T09:32:48.737879,2,...,France,1000468,Ivan Hašek,None,1963-09-06,60,Czech Republic,1.1.0,2,2
10,3938639,2024-06-18,16:00:00.000,3,1,available,available,2026-05-01T09:28:22.819373,2026-05-01T09:31:07.904688,1,...,Italy,752,Willy Sagnol,None,1977-03-18,78,France,1.1.0,2,2
11,3938638,2024-06-17,13:00:00.000,3,0,available,available,2026-05-01T09:27:13.675842,2026-05-01T09:28:09.895197,1,...,Romania,2672,Sergiy Rebrov,None,1974-06-03,238,Ukraine,1.1.0,2,2
12,3938640,2024-06-21,13:00:00.000,1,2,available,available,2026-05-01T09:30:25.947399,2026-05-01T09:33:19.373847,2,...,Italy,2672,Sergiy Rebrov,None,1974-06-03,238,Ukraine,1.1.0,2,2
13,3938637,2024-06-16,13:00:00.000,1,2,available,available,2026-05-01T09:26:08.384231,2026-05-01T09:28:38.742295,1,...,Poland,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
14,3938644,2024-06-26,19:00:00.000,2,0,available,available,2026-05-01T09:33:42.825432,2026-05-01T09:35:37.929565,3,...,France,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1.1.0,2,2
15,3941019,2024-07-01,16:00:00.000,1,0,available,available,2026-04-28T18:43:38.448635,2026-04-28T18:46:34.258160,4,...,France,48,Domenico Tedesco,None,1985-09-12,85,Germany,1.1.0,2,2
16,3942227,2024-07-06,16:00:00.000,1,1,available,available,2026-04-28T18:36:59.072443,2026-04-28T18:37:57.405782,5,...,England,2832,Murat Yakin,None,1974-09-15,221,Switzerland,1.1.0,2,2
17,3930174,2024-06-22,16:00:00.000,0,3,available,available,2026-05-01T19:53:20.935581,2026-05-01T19:55:23.536920,2,...,Italy,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1.1.0,2,2
18,3930162,2024-06-16,16:00:00.000,1,1,available,available,2026-05-01T19:49:21.493258,2026-05-01T19:50:25.968394,1,...,Slovenia,255,Kasper Hjulmand,None,1972-04-09,61,Denmark,1.1.0,2,2
19,3930176,2024-06-23,19:00:00.000,1,1,available,available,2026-05-01T19:54:25.846072,2026-05-01T19:58:06.077979,3,...,Switzerland,445,Julian Nagelsmann,None,1987-07-23,85,Germany,1.1.0,2,2
20,3930169,2024-06-19,19:00:00.000,1,1,available,available,2026-05-01T19:45:31.930120,2026-05-01T19:47:44.634200,2,...,Scotland,2832,Murat Yakin,None,1974-09-15,221,Switzerland,1.1.0,2,2
21,3942819,2024-07-10,19:00:00.000,1,2,available,available,2026-04-29T01:44:42.908892,2026-04-29T01:45:55.922658,6,...,Netherlands,277,Gareth Southgate,None,1970-09-03,68,England,1.1.0,2,2
22,3943043,2024-07-14,19:00:00.000,2,1,available,available,2026-04-29T01:45:39.959110,2026-04-29T01:48:42.195978,7,...,Spain,277,Gareth Southgate,None,1970-09-03,68,England,1.1.0,2,2
23,3942752,2024-07-09,19:00:00.000,2,1,available,available,2026-04-29T01:43:46.587696,2026-04-29T01:46:24.320801,6,...,Spain,545,Didier Deschamps,None,1968-10-15,78,France,1.1.0,2,2
24,3942382,2024-07-06,19:00:00.000,2,1,available,available,2026-04-29T01:42:47.615163,2026-04-29T01:43:21.624446,5,...,Netherlands,232,Vincenzo Montella,None,1974-06-18,112,Italy,1.1.0,2,2
25,3942349,2024-07-05,19:00:00.000,0,0,available,available,2026-04-29T01:41:50.982383,2026-04-29T01:43:49.615367,5,...,Spain,545,Didier Deschamps,None,1968-10-15,78,France,1.1.0,2,2
26,3930180,2024-06-25,16:00:00.000,2,3,available,available,2026-05-01T19:49:21.034035,2026-05-01T19:51:01.462993,3,...,Netherlands,380,Ralf Rangnick,None,1958-06-29,85,Germany,1.1.0,2,2
27,3930171,2024-06-20,16:00:00.000,1,1,available,available,2026-05-01T19:47:51.892574,2026-05-01T19:52:26.864280,2,...,Denmark,277,Gareth Southgate,None,1970-09-03,68,England,1.1.0,2,2
28,3942226,2024-07-05,16:00:00.000,2,1,available,available,2026-04-28T18:47:02.268381,2026-04-28T18:48:13.592837,5,...,Spain,445,Julian Nagelsmann,None,1987-07-23,85,Germany,1.1.0,2,2
29,3938645,2024-06-26,16:00:00.000,0,0,available,available,2026-05-01T09:34:44.803734,2026-05-01T09:36:29.685734,3,...,Ukraine,48,Domenico Tedesco,None,1985-09-12,85,Germany,1.1.0,2,2
30,3930184,2024-06-26,22:00:00.000,1,2,available,available,2024-08-15T15:36:29.017341,2024-09-09T09:27:36.815106,3,...,Czech Republic,232,Vincenzo Montella,None,1974-06-18,112,Italy,1.1.0,2,2
31,3941022,2024-07-02,19:00:00.000,1,2,available,available,2026-04-28T18:45:46.987394,2026-04-28T18:48:43.304922,4,...,Germany,232,Vincenzo Montella,None,1974-06-18,112,Italy,1.1.0,2,2
32,3941021,2024-07-02,16:00:00.000,0,3,available,available,2026-04-28T18:44:35.399441,2026-04-28T18:46:09.953777,4,...,Romania,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
33,3941020,2024-07-01,19:00:00.000,0,0,available,available,2026-04-28T18:42:19.506332,2026-04-28T18:43:22.855246,4,...,Spain,1733,Matjaž Kek,None,1961-09-09,208,Slovenia,1.1.0,2,2
34,3941018,2024-06-30,19:00:00.000,4,1,available,available,2026-04-28T18:39:39.065203,2026-04-28T18:40:26.717452,4,...,Spain,752,Willy Sagnol,None,1977-03-18,78,France,1.1.0,2,2
35,3941017,2024-06-30,16:00:00.000,2,1,available,available,2026-04-28T18:41:06.699931,2026-04-28T18:44:10.985963,4,...,England,1002171,Francesco Calzona,None,1968-10-24,112,Italy,1.1.0,2,2
36,3930182,2024-06-25,19:00:00.000,0,0,available,available,2026-05-01T19:47:28.693557,2026-05-01T19:50:34.375873,3,...,Denmark,5908,Dragan Stojković,None,1965-03-03,203,Serbia,1.1.0,2,2
37,3930179,2024-06-24,19:00:00.000,0,1,available,available,2026-05-01T19:46:24.060159,2026-05-01T19:51:26.189211,3,...,Brazil,5588,Luis de la Fuente Castillo,Luis de la Fuente,1961-06-21,214,Spain,1.1.0,2,2
38,3940983,2024-06-29,19:00:00.000,2,0,available,available,2026-04-28T18:38:21.125369,2026-04-28T18:40:57.190664,4,...,Germany,255,Kasper Hjulmand,None,1972-04-09,61,Denmark,1.1.0,2,2
39,3940878,2024-06-29,16:00:00.000,2,0,available,available,2026-04-28T18:37:13.038356,2026-04-28T18:38:32.857625,4,...,Switzerland,399,Luciano Spalletti,None,1959-03-07,112,Italy,1.1.0,2,2
40,3930177,2024-06-23,19:00:00.000,0,1,available,available,2026-05-01T19:44:18.003020,2026-05-01T19:47:15.307446,3,...,Scotland,3616,Marco Rossi,None,1964-09-09,112,Italy,1.1.0,2,2
41,3930173,2024-06-21,19:00:00.000,0,0,available,available,2026-05-01T19:51:17.821277,2026-05-01T19:55:53.005892,2,...,Netherlands,545,Didier Deschamps,None,1968-10-15,78,France,1.1.0,2,2
42,3930172,2024-06-20,19:00:00.000,1,0,available,available,2026-05-01T19:49:03.402539,2026-05-01T19:51:56.234934,2,...,Spain,399,Luciano Spalletti,None,1959-03-07,112,Italy,1.1.0,2,2
43,3930167,2024-06-19,13:00:00.000,2,2,available,available,2026-05-01T19:44:26.796333,2026-05-01T19:48:07.889956,2,...,Croatia,1877,Sylvio Mendes Campos Junior,Sylvinho,1974-04-12,31,Brazil,1.1.0,2,2
44,3930168,2024-06-19,16:00:00.000,2,0,available,available,2026-05-01T19:46:44.244653,2026-05-01T19:52:50.304198,2,...,Germany,3616,Marco Rossi,None,1964-09-09,112,Italy,1.1.0,2,2
45,3930165,2024-06-17,19:00:00.000,0,1,available,available,2026-05-01T19:50:29.633847,2026-05-01T19:54:15.076346,1,...,Germany,545,Didier Deschamps,None,1968-10-15,78,France,1.1.0,2,2
46,3930164,2024-06-17,16:00:00.000,0,1,available,available,2026-05-01T19:51:32.944920,2026-05-01T19:54:50.996052,1,...,Germany,1002171,Francesco Calzona,None,1968-10-24,112,Italy,1.1.0,2,2
47,3930161,2024-06-15,19:00:00.000,2,1,available,available,2026-05-01T19:47:11.911723,2026-05-01T19:51:21.306089,1,...,Italy,1877,Sylvio Mendes Campos Junior,Sylvinho,1974-04-12,31,Brazil,1.1.0,2,2
48,3930183,2024-06-26,16:00:00.000,1,1,available,available,2026-05-01T19:50:13.356763,2026-05-01T19:54:31.470252,3,...,Italy,6237,Edward Iordănescu,None,1978-06-16,187,Romania,1.1.0,2,2
49,3930175,2024-06-22,19:00:00.000,2,0,available,available,2026-05-01T19:52:16.451217,2026-05-01T19:54:56.604789,2,...,Germany,6237,Edward Iordănescu,None,1978-06-16,187,Romania,1.1.0,2,2
50,3930158,2024-06-14,19:00:00.000,5,1,available,available,2026-05-01T19:43:49.048383,2026-05-01T19:44:28.668814,1,...,Germany,510,Steve Clarke,None,1963-08-29,201,Scotland,1.1.0,2,2

In [13]:
all_lineups = []

# iterar sobre os jogos para obter os lineups
for _, match in matches_df.iterrows():

    match_id = match["match_id"]

    lineup_dict = sb.lineups(match_id=match_id)

    team_mapping = {
        match["home_team"]: match["home_team_id"],
        match["away_team"]: match["away_team_id"]
    }

    for team_name, lineup_df in lineup_dict.items():

        lineup_df = lineup_df.copy()

        lineup_df["team_name"] = team_name
        lineup_df["team_id"] = team_mapping.get(team_name)
        lineup_df["match_id"] = match_id

        all_lineups.append(lineup_df)

lineups_df = pd.concat(all_lineups, ignore_index=True)

# guardar os dados raw dos lineups
lineups_df.to_parquet("../data/raw/lineups.parquet", index=False)
lineups_df

,player_id,player_name,player_nickname,jersey_number,country,cards,positions,team_name,team_id,match_id
0,3193,Bernardo Mota Veiga de Carvalho e Silva,Bernardo Silva,10,Portugal,[],"[{'position_id': 19, 'position': 'Center Attac...",Portugal,780,3930166
1,5204,Bruno Miguel Borges Fernandes,Bruno Fernandes,8,Portugal,[],"[{'position_id': 11, 'position': 'Left Defensi...",Portugal,780,3930166
2,5205,Rui Pedro dos Santos Patrício,Rui Patrício,1,Portugal,[],[],Portugal,780,3930166
3,5206,Rúben Santos Gato Alves Dias,Rúben Dias,4,Portugal,[],"[{'position_id': 3, 'position': 'Right Center ...",Portugal,780,3930166
4,5207,Cristiano Ronaldo dos Santos Aveiro,Cristiano Ronaldo,7,Portugal,[],"[{'position_id': 22, 'position': 'Right Center...",Portugal,780,3930166
...,...,...,...,...,...,...,...,...,...,...
2582,22308,Anthony Ralston,None,2,Scotland,"[{'time': '47:19', 'card_type': 'Yellow Card',...","[{'position_id': 7, 'position': 'Right Wing Ba...",Scotland,942,3930158
2583,22379,Angus Gunn,None,1,Scotland,[],"[{'position_id': 1, 'position': 'Goalkeeper', ...",Scotland,942,3930158
2584,31067,Billy Gilmour,None,14,Scotland,[],"[{'position_id': 10, 'position': 'Center Defen...",Scotland,942,3930158
2585,38169,Lawrence Shankland,None,9,Scotland,[],"[{'position_id': 23, 'position': 'Center Forwa...",Scotland,942,3930158
2586,49720,Tommy Conway,None,19,Scotland,[],[],Scotland,942,3930158

In [14]:
# função para obter eventos com base em lista de match_ids
def get_all_events(match_ids):

    all_events = []

    for match_id in tqdm(match_ids):

        try:
            events_df = sb.events(match_id=match_id)

            # events_df["home_team"] = match["home_team"]
            # events_df["away_team"] = match["away_team"]
            # events_df["competition"] = match.get("competition_name", None)
            # events_df["season"] = match.get("season_name", None)

            all_events.append(events_df)

        except Exception as e:
            print(f"Error loading {match_id}: {e}")

    return pd.concat(all_events, ignore_index=True)


events_df = get_all_events(matches_df["match_id"])
events_df

100%|██████████| 51/51 [00:33<00:00,  1.51it/s]

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,...,foul_committed_penalty,foul_won_penalty,pass_deflected,shot_redirect,goalkeeper_punched_out,shot_open_goal,block_save_block,goalkeeper_success_in_play,goalkeeper_penalty_saved_to_post,shot_follows_dribble
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# função para obter dados 360 com base em lista de match_ids
def get_all_frames(match_ids):

    all_frames = []

    for match_id in tqdm(match_ids):

        try:
            frames_df = sb.frames(match_id=match_id)

            all_frames.append(frames_df)

        except Exception as e:
            print(f"Error loading {match_id}: {e}")

    return pd.concat(all_frames, ignore_index=True)

events_360_df = get_all_frames(matches_df["match_id"])
events_360_df

100%|██████████| 51/51 [01:11<00:00,  1.41s/it]

,id,visible_area,match_id,teammate,actor,keeper,location
0,87a790b7-17a6-4bbd-953f-a06c07edbad9,"[18.400697860849267, 80.0, 46.48865423106284, ...",3930166,True,False,False,"[38.20338261131079, 29.491675823953365]"
1,87a790b7-17a6-4bbd-953f-a06c07edbad9,"[18.400697860849267, 80.0, 46.48865423106284, ...",3930166,True,False,False,"[40.435487610014256, 49.496164383322295]"
2,87a790b7-17a6-4bbd-953f-a06c07edbad9,"[18.400697860849267, 80.0, 46.48865423106284, ...",3930166,True,False,False,"[51.887832712562904, 56.43639891583137]"
3,87a790b7-17a6-4bbd-953f-a06c07edbad9,"[18.400697860849267, 80.0, 46.48865423106284, ...",3930166,True,False,False,"[60.036085232306185, 31.006609171941484]"
4,87a790b7-17a6-4bbd-953f-a06c07edbad9,"[18.400697860849267, 80.0, 46.48865423106284, ...",3930166,True,False,False,"[60.838859912993875, 4.272189145609488]"
...,...,...,...,...,...,...,...
2698994,5ce3666b-f6c5-4426-a16c-7928236bbdac,"[0.0, 80.0, 0.0, 28.23202227625909, 22.9743547...",3930158,True,False,False,"[15.948856551775805, 55.95216286228902]"
2698995,5ce3666b-f6c5-4426-a16c-7928236bbdac,"[0.0, 80.0, 0.0, 28.23202227625909, 22.9743547...",3930158,False,False,False,"[17.452580090224245, 33.005712133560706]"
2698996,5ce3666b-f6c5-4426-a16c-7928236bbdac,"[0.0, 80.0, 0.0, 28.23202227625909, 22.9743547...",3930158,False,False,False,"[19.947396309933282, 45.41233704070139]"
2698997,5ce3666b-f6c5-4426-a16c-7928236bbdac,"[0.0, 80.0, 0.0, 28.23202227625909, 22.9743547...",3930158,True,False,False,"[20.328016357383106, 42.49520526434236]"
2698998,5ce3666b-f6c5-4426-a16c-7928236bbdac,"[0.0, 80.0, 0.0, 28.23202227625909, 22.9743547...",3930158,False,False,False,"[27.303963268629587, 37.671268480704946]"

In [16]:
# eliminar coluna para evitar conflitos de duplicação de colunas após o merge
events_360_df = events_360_df.drop(columns=["match_id"], errors="ignore")

# realizamos o merge dos eventos com os dados 360º através do id do evento
events_df = events_df.merge(events_360_df, on="id", how="left")

# guardar os dados raw dos eventos (eventos + 360)
events_df.to_parquet("../data/raw/events.parquet", index=False)
events_df

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,...,shot_open_goal,block_save_block,goalkeeper_success_in_play,goalkeeper_penalty_saved_to_post,shot_follows_dribble,visible_area,teammate,actor,keeper,location_y
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2722388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[29.752411154964918, 79.22086739213373, 0.0, 4...",False,False,False,"[17.191577570485677, 42.22972347817744]"
2722389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[29.752411154964918, 79.22086739213373, 0.0, 4...",True,False,False,"[17.965696465999017, 29.694118095738418]"
2722390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[29.752411154964918, 79.22086739213373, 0.0, 4...",True,False,False,"[25.70225726023301, 36.307377809078865]"
2722391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[29.752411154964918, 79.22086739213373, 0.0, 4...",False,False,False,"[30.580730722937282, 47.8590938785301]"
2722392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[29.752411154964918, 79.22086739213373, 0.0, 4...",True,False,False,"[37.21744231751122, 59.8941166423611]"