In [1]:
import pandas as pd
import numpy as np
from statsbombpy import sb
import warnings
from tqdm import tqdm
warnings.filterwarnings("ignore")

/Users/goncalo.rodrigues9/Desktop/SC Braga/GR/Custom360_Bundesliga_Metrics/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
pd.set_option("display.max_columns", None)

In [3]:
def get_competitions(competition_season_pairs):
    comps_df = sb.competitions()

    mask = False

    for competition_name, season_name in competition_season_pairs:
        mask |= (
            (comps_df["competition_name"] == competition_name) &
            (comps_df["season_name"] == season_name)
        )

    return comps_df[mask]

In [4]:
competitions = [
    #("1. Bundesliga", "2023/2024"),
    #("Ligue 1", "2015/2016"),
    ("UEFA Euro", "2024")
    #("La Liga", "2019/2020"),
    #("Champions League", "2018/2019")
    #("African Cup of Nations", "2023")
]

competitions_df = get_competitions(competitions)
competitions_df.to_parquet("../data/raw/competitions.parquet", index=False)
competitions_df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
73,55,282,Europe,UEFA Euro,male,False,True,2024,2026-05-01T19:54:25.846072,2026-05-01T19:58:06.077979,2026-05-01T19:58:06.077979,2026-05-01T19:54:25.846072

In [5]:
matches_dfs = []

for _, row in competitions_df.iterrows():
    matches = sb.matches(
        competition_id=row["competition_id"],
        season_id=row["season_id"]
    )

    matches_dfs.append(matches)

matches_df = pd.concat(matches_dfs, ignore_index=True)
matches_df.to_parquet("../data/raw/matches.parquet", index=False)
matches_df

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_id,competition_country_name,competition_name,competition,season_id,season,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3930166,2024-06-18,19:00:00.000,2,1,available,available,2026-05-01T19:52:36.631184,2026-05-01T19:56:35.877702,1,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,780,Portugal,male,None,183,Portugal,912,Czech Republic,male,None,60,Czech Republic,10,Group Stage,376,Red Bull Arena,85,Germany,261,Marco Guida,112,Italy,Roberto Martínez Montoliú,Ivan Hašek,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1000468,Ivan Hašek,None,1963-09-06,60,Czech Republic,1.1.0,2,2
1,3930159,2024-06-15,13:00:00.000,1,3,available,available,2026-05-01T19:45:59.392947,2026-05-01T19:50:52.970161,1,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,916,Hungary,male,None,103,Hungary,773,Switzerland,male,None,221,Switzerland,10,Group Stage,363,RheinEnergieStadion,85,Germany,943,Slavko Vinčić,208,Slovenia,Marco Rossi,Murat Yakin,3616,Marco Rossi,None,1964-09-09,112,Italy,2832,Murat Yakin,None,1974-09-15,221,Switzerland,1.1.0,2,2
2,3930163,2024-06-16,19:00:00.000,0,1,available,available,2026-05-01T19:48:19.783129,2026-05-01T19:49:47.226912,1,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,786,Serbia,male,None,203,Serbia,768,England,male,None,68,England,10,Group Stage,370,VELTINS-Arena,85,Germany,269,Daniele Orsato,112,Italy,Dragan Stojković,Gareth Southgate,5908,Dragan Stojković,None,1965-03-03,203,Serbia,277,Gareth Southgate,None,1970-09-03,68,England,1.1.0,2,2
3,3930181,2024-06-25,19:00:00.000,0,0,available,available,2026-05-01T19:48:27.887397,2026-05-01T19:50:03.279607,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,768,England,male,None,68,England,944,Slovenia,male,None,208,Slovenia,10,Group Stage,363,RheinEnergieStadion,85,Germany,76,Clément Turpin,78,France,Gareth Southgate,Matjaž Kek,277,Gareth Southgate,None,1970-09-03,68,England,1733,Matjaž Kek,None,1961-09-09,208,Slovenia,1.1.0,2,2
4,3930178,2024-06-24,19:00:00.000,1,1,available,available,2026-05-01T19:45:23.956799,2026-05-01T19:46:35.413328,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,785,Croatia,male,None,56,Croatia,914,Italy,male,None,112,Italy,10,Group Stage,376,Red Bull Arena,85,Germany,293,Danny Desmond Makkelie,160,Netherlands,Zlatko Dalić,Luciano Spalletti,307,Zlatko Dalić,None,1966-10-26,56,Croatia,399,Luciano Spalletti,None,1959-03-07,112,Italy,1.1.0,2,2
5,3930160,2024-06-15,16:00:00.000,3,0,available,available,2026-05-01T19:45:01.052020,2026-05-01T19:46:14.941863,1,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,772,Spain,male,None,214,Spain,785,Croatia,male,None,56,Croatia,10,Group Stage,367,Olympiastadion Berlin,85,Germany,1,Michael Oliver,68,England,Luis de la Fuente Castillo,Zlatko Dalić,5588,Luis de la Fuente Castillo,Luis de la Fuente,1961-06-21,214,Spain,307,Zlatko Dalić,None,1966-10-26,56,Croatia,1.1.0,2,2
6,3930170,2024-06-20,13:00:00.000,1,1,available,available,2026-05-01T19:50:11.398180,2026-05-01T19:56:14.983173,2,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,944,Slovenia,male,None,208,Slovenia,786,Serbia,male,None,203,Serbia,10,Group Stage,4867,Allianz Arena,85,Germany,1011397,István Kovács,187,Romania,Matjaž Kek,Dragan Stojković,1733,Matjaž Kek,None,1961-09-09,208,Slovenia,5908,Dragan Stojković,None,1965-03-03,203,Serbia,1.1.0,2,2
7,3938643,2024-06-25,16:00:00.000,1,1,available,available,2026-05-01T09:32:36.453598,2026-05-01T09:37:02.207863,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,771,France,male,None,78,France,789,Poland,male,None,182,Poland,10,Group Stage,373,Signal-Iduna-Park,85,Germany,261,Marco Guida,112,Italy,Didier Deschamps,Michał Probierz,545,Didier Deschamps,None,1968-10-15,78,France,363,Michał Probierz,None,1972-09-24,182,Poland,1.1.0,2,2
8,3938641,2024-06-21,16:00:00.000,1,3,available,available,2026-05-01T09:29:24.560133,2026-05-01T09:30:43.170204,2,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,789,Poland,male,None,182,Poland,915,Austria,male,None,15,Austria,10,Group Stage,367,Olympiastadion Berlin,85,Germany,845,Halil Umut Meler,233,Turkey,Michał Probierz,Ralf Rangnick,363,Michał Probierz,None,1972-09-24,182,Poland,380,Ralf Rangnick,None,1958-06-29,85,Germany,1.1.0,2,2
9,3938642,2024-06-22,13:00:00.000,1,1,available,available,2026-05-01T09:31:28.135473,2026-05-01T09:32:48.737879,2,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,2138,Georgia,male,None,84,Georgia,912,Czech Republic,male,None,60,Czech Republic,10,Group Stage,379,Volksparkstadion,85,Germany,225,Daniel Siebert,85,Germany,Willy Sagnol,Ivan Hašek,752,Willy Sagnol,None,1977-03-18,78,France,1000468,Ivan Hašek,None,1963-09-06,60,Czech Republic,1.1.0,2,2
10,3938639,2024-06-18,16:00:00.000,3,1,available,available,2026-05-01T09:28:22.819373,2026-05-01T09:31:07.904688,1,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,909,Turkey,male,None,233,Turkey,2138,Georgia,male,None,84,Georgia,10,Group Stage,373,Signal-Iduna-Park,85,Germany,1094,Facundo Tello Figueroa,11,Argentina,Vincenzo Montella,Willy Sagnol,232,Vincenzo Montella,None,1974-06-18,112,Italy,752,Willy Sagnol,None,1977-03-18,78,France,1.1.0,2,2
11,3938638,2024-06-17,13:00:00.000,3,0,available,available,2026-05-01T09:27:13.675842,2026-05-01T09:28:09.895197,1,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,905,Romania,male,None,187,Romania,911,Ukraine,male,None,238,Ukraine,10,Group Stage,4867,Allianz Arena,85,Germany,1062,Glenn Nyberg,220,Sweden,Edward Iordănescu,Sergiy Rebrov,6237,Edward Iordănescu,None,1978-06-16,187,Romania,2672,Sergiy Rebrov,None,1974-06-03,238,Ukraine,1.1.0,2,2
12,3938640,2024-06-21,13:00:00.000,1,2,available,available,2026-05-01T09:30:25.947399,2026-05-01T09:33:19.373847,2,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,908,Slovakia,male,None,207,Slovakia,911,Ukraine,male,None,238,Ukraine,10,Group Stage,4866,Merkur Spiel-Arena,85,Germany,1,Michael Oliver,68,England,Francesco Calzona,Sergiy Rebrov,1002171,Francesco Calzona,None,1968-10-24,112,Italy,2672,Sergiy Rebrov,None,1974-06-03,238,Ukraine,1.1.0,2,2
13,3938637,2024-06-16,13:00:00.000,1,2,available,available,2026-05-01T09:26:08.384231,2026-05-01T09:28:38.742295,1,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,789,Poland,male,None,182,Poland,941,Netherlands,male,None,160,Netherlands,10,Group Stage,379,Volksparkstadion,85,Germany,2445,Artur Manuel Ribeiro Soares Dias,183,Portugal,Michał Probierz,Ronald Koeman,363,Michał Probierz,None,1972-09-24,182,Poland,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
14,3938644,2024-06-26,19:00:00.000,2,0,available,available,2026-05-01T09:33:42.825432,2026-05-01T09:35:37.929565,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,2138,Georgia,male,None,84,Georgia,780,Portugal,male,None,183,Portugal,10,Group Stage,370,VELTINS-Arena,85,Germany,116,Sandro Schärer,221,Switzerland,Willy Sagnol,Roberto Martínez Montoliú,752,Willy Sagnol,None,1977-03-18,78,France,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1.1.0,2,2
15,3941019,2024-07-01,16:00:00.000,1,0,available,available,2026-04-28T18:43:38.448635,2026-04-28T18:46:34.258160,4,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,771,France,male,None,78,France,782,Belgium,male,None,22,Belgium,33,Round of 16,4866,Merkur Spiel-Arena,85,Germany,1062,Glenn Nyberg,220,Sweden,Didier Deschamps,Domenico Tedesco,545,Didier Deschamps,None,1968-10-15,78,France,48,Domenico Tedesco,None,1985-09-12,85,Germany,1.1.0,2,2
16,3942227,2024-07-06,16:00:00.000,1,1,available,available,2026-04-28T18:36:59.072443,2026-04-28T18:37:57.405782,5,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,768,England,male,None,68,England,773,Switzerland,male,None,221,Switzerland,11,Quarter-finals,4866,Merkur Spiel-Arena,85,Germany,269,Daniele Orsato,112,Italy,Gareth Southgate,Murat Yakin,277,Gareth Southgate,None,1970-09-03,68,England,2832,Murat Yakin,None,1974-09-15,221,Switzerland,1.1.0,2,2
17,3930174,2024-06-22,16:00:00.000,0,3,available,available,2026-05-01T19:53:20.935581,2026-05-01T19:55:23.536920,2,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,909,Turkey,male,None,233,Turkey,780,Portugal,male,None,183,Portugal,10,Group Stage,373,Signal-Iduna-Park,85,Germany,241,Felix Zwayer,85,Germany,Vincenzo Montella,Roberto Martínez Montoliú,232,Vincenzo Montella,None,1974-06-18,112,Italy,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1.1.0,2,2
18,3930162,2024-06-16,16:00:00.000,1,1,available,available,2026-05-01T19:49:21.493258,2026-05-01T19:50:25.968394,1,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,944,Slovenia,male,None,208,Slovenia,776,Denmark,male,None,61,Denmark,10,Group Stage,369,MHPArena,85,Germany,116,Sandro Schärer,221,Switzerland,Matjaž Kek,Kasper Hjulmand,1733,Matjaž Kek,None,1961-09-09,208,Slovenia,255,Kasper Hjulmand,None,1972-04-09,61,Denmark,1.1.0,2,2
19,3930176,2024-06-23,19:00:00.000,1,1,available,available,2026-05-01T19:54:25.846072,2026-05-01T19:58:06.077979,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,773,Switzerland,male,None,221,Switzerland,770,Germany,male,None,85,Germany,10,Group Stage,116458,Deutsche Bank Park,85,Germany,269,Daniele Orsato,112,Italy,Murat Yakin,Julian Nagelsmann,2832,Murat Yakin,None,1974-09-15,221,Switzerland,445,Julian Nagelsmann,None,1987-07-23,85,Germany,1.1.0,2,2
20,3930169,2024-06-19,19:00:00.000,1,1,available,available,2026-05-01T19:45:31.930120,2026-05-01T19:47:44.634200,2,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,942,Scotland,male,None,201,Scotland,773,Switzerland,male,None,221,Switzerland,10,Group Stage,363,RheinEnergieStadion,85,Germany,941,Ivan Kružliak,207,Slovakia,Steve Clarke,Murat Yakin,510,Steve Clarke,None,1963-08-29,201,Scotland,2832,Murat Yakin,None,1974-09-15,221,Switzerland,1.1.0,2,2
21,3942819,2024-07-10,19:00:00.000,1,2,available,available,2026-04-29T01:44:42.908892,2026-04-29T01:45:55.922658,6,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,941,Netherlands,male,None,160,Netherlands,768,England,male,None,68,England,15,Semi-finals,373,Signal-Iduna-Park,85,Germany,241,Felix Zwayer,85,Germany,Ronald Koeman,Gareth Southgate,676,Ronald Koeman,None,1963-03-21,160,Netherlands,277,Gareth Southgate,None,1970-09-03,68,England,1.1.0,2,2
22,3943043,2024-07-14,19:00:00.000,2,1,available,available,2026-04-29T01:45:39.959110,2026-04-29T01:48:42.195978,7,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,772,Spain,male,None,214,Spain,768,England,male,None,68,England,26,Final,367,Olympiastadion Berlin,85,Germany,79,François Letexier,78,France,Luis de la Fuente Castillo,Gareth Southgate,5588,Luis de la Fuente Castillo,Luis de la Fuente,1961-06-21,214,Spain,277,Gareth Southgate,None,1970-09-03,68,England,1.1.0,2,2
23,3942752,2024-07-09,19:00:00.000,2,1,available,available,2026-04-29T01:43:46.587696,2026-04-29T01:46:24.320801,6,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,772,Spain,male,None,214,Spain,771,France,male,None,78,France,15,Semi-finals,4867,Allianz Arena,85,Germany,943,Slavko Vinčić,208,Slovenia,Luis de la Fuente Castillo,Didier Deschamps,5588,Luis de la Fuente Castillo,Luis de la Fuente,1961-06-21,214,Spain,545,Didier Deschamps,None,1968-10-15,78,France,1.1.0,2,2
24,3942382,2024-07-06,19:00:00.000,2,1,available,available,2026-04-29T01:42:47.615163,2026-04-29T01:43:21.624446,5,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,941,Netherlands,male,None,160,Netherlands,909,Turkey,male,None,233,Turkey,11,Quarter-finals,367,Olympiastadion Berlin,85,Germany,76,Clément Turpin,78,France,Ronald Koeman,Vincenzo Montella,676,Ronald Koeman,None,1963-03-21,160,Netherlands,232,Vincenzo Montella,None,1974-06-18,112,Italy,1.1.0,2,2
25,3942349,2024-07-05,19:00:00.000,0,0,available,available,2026-04-29T01:41:50.982383,2026-04-29T01:43:49.615367,5,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,780,Portugal,male,None,183,Portugal,771,France,male,None,78,France,11,Quarter-finals,379,Volksparkstadion,85,Germany,1,Michael Oliver,68,England,Roberto Martínez Montoliú,Didier Deschamps,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,545,Didier Deschamps,None,1968-10-15,78,France,1.1.0,2,2
26,3930180,2024-06-25,16:00:00.000,2,3,available,available,2026-05-01T19:49:21.034035,2026-05-01T19:51:01.462993,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,941,Netherlands,male,None,160,Netherlands,915,Austria,male,None,15,Austria,10,Group Stage,367,Olympiastadion Berlin,85,Germany,941,Ivan Kružliak,207,Slovakia,Ronald Koeman,Ralf Rangnick,676,Ronald Koeman,None,1963-03-21,160,Netherlands,380,Ralf Rangnick,None,1958-06-29,85,Germany,1.1.0,2,2
27,3930171,2024-06-20,16:00:00.000,1,1,available,available,2026-05-01T19:47:51.892574,2026-05-01T19:52:26.864280,2,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,776,Denmark,male,None,61,Denmark,768,England,male,None,68,England,10,Group Stage,116458,Deutsche Bank Park,85,Germany,2445,Artur Manuel Ribeiro Soares Dias,183,Portugal,Kasper Hjulmand,Gareth Southgate,255,Kasper Hjulmand,None,1972-04-09,61,Denmark,277,Gareth Southgate,None,1970-09-03,68,England,1.1.0,2,2
28,3942226,2024-07-05,16:00:00.000,2,1,available,available,2026-04-28T18:47:02.268381,2026-04-28T18:48:13.592837,5,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,772,Spain,male,None,214,Spain,770,Germany,male,None,85,Germany,11,Quarter-finals,369,MHPArena,85,Germany,8,Anthony Taylor,68,England,Luis de la Fuente Castillo,Julian Nagelsmann,5588,Luis de la Fuente Castillo,Luis de la Fuente,1961-06-21,214,Spain,445,Julian Nagelsmann,None,1987-07-23,85,Germany,1.1.0,2,2
29,3938645,2024-06-26,16:00:00.000,0,0,available,available,2026-05-01T09:34:44.803734,2026-05-01T09:36:29.685734,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,911,Ukraine,male,None,238,Ukraine,782,Belgium,male,None,22,Belgium,10,Group Stage,369,MHPArena,85,Germany,8,Anthony Taylor,68,England,Sergiy Rebrov,Domenico Tedesco,2672,Sergiy Rebrov,None,1974-06-03,238,Ukraine,48,Domenico Tedesco,None,1985-09-12,85,Germany,1.1.0,2,2
30,3930184,2024-06-26,22:00:00.000,1,2,available,available,2024-08-15T15:36:29.017341,2024-09-09T09:27:36.815106,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,912,Czech Republic,male,None,60,Czech Republic,909,Turkey,male,None,233,Turkey,10,Group Stage,379,Volksparkstadion,85,Germany,1011397,István Kovács,187,Romania,Ivan Hašek,Vincenzo Montella,1000468,Ivan Hašek,None,1963-09-06,60,Czech Republic,232,Vincenzo Montella,None,1974-06-18,112,Italy,1.1.0,2,2
31,3941022,2024-07-02,19:00:00.000,1,2,available,available,2026-04-28T18:45:46.987394,2026-04-28T18:48:43.304922,4,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,915,Austria,male,None,15,Austria,909,Turkey,male,None,233,Turkey,33,Round of 16,376,Red Bull Arena,85,Germany,2445,Artur Manuel Ribeiro Soares Dias,183,Portugal,Ralf Rangnick,Vincenzo Montella,380,Ralf Rangnick,None,1958-06-29,85,Germany,232,Vincenzo Montella,None,1974-06-18,112,Italy,1.1.0,2,2
32,3941021,2024-07-02,16:00:00.000,0,3,available,available,2026-04-28T18:44:35.399441,2026-04-28T18:46:09.953777,4,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,905,Romania,male,None,187,Romania,941,Netherlands,male,None,160,Netherlands,33,Round of 16,4867,Allianz Arena,85,Germany,241,Felix Zwayer,85,Germany,Edward Iordănescu,Ronald Koeman,6237,Edward Iordănescu,None,1978-06-16,187,Romania,676,Ronald Koeman,None,1963-03-21,160,Netherlands,1.1.0,2,2
33,3941020,2024-07-01,19:00:00.000,0,0,available,available,2026-04-28T18:42:19.506332,2026-04-28T18:43:22.855246,4,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,780,Portugal,male,None,183,Portugal,944,Slovenia,male,None,208,Slovenia,33,Round of 16,116458,Deutsche Bank Park,85,Germany,269,Daniele Orsato,112,Italy,Roberto Martínez Montoliú,Matjaž Kek,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1733,Matjaž Kek,None,1961-09-09,208,Slovenia,1.1.0,2,2
34,3941018,2024-06-30,19:00:00.000,4,1,available,available,2026-04-28T18:39:39.065203,2026-04-28T18:40:26.717452,4,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,772,Spain,male,None,214,Spain,2138,Georgia,male,None,84,Georgia,33,Round of 16,363,RheinEnergieStadion,85,Germany,79,François Letexier,78,France,Luis de la Fuente Castillo,Willy Sagnol,5588,Luis de la Fuente Castillo,Luis de la Fuente,1961-06-21,214,Spain,752,Willy Sagnol,None,1977-03-18,78,France,1.1.0,2,2
35,3941017,2024-06-30,16:00:00.000,2,1,available,available,2026-04-28T18:41:06.699931,2026-04-28T18:44:10.985963,4,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,768,England,male,None,68,England,908,Slovakia,male,None,207,Slovakia,33,Round of 16,370,VELTINS-Arena,85,Germany,845,Halil Umut Meler,233,Turkey,Gareth Southgate,Francesco Calzona,277,Gareth Southgate,None,1970-09-03,68,England,1002171,Francesco Calzona,None,1968-10-24,112,Italy,1.1.0,2,2
36,3930182,2024-06-25,19:00:00.000,0,0,available,available,2026-05-01T19:47:28.693557,2026-05-01T19:50:34.375873,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,776,Denmark,male,None,61,Denmark,786,Serbia,male,None,203,Serbia,10,Group Stage,4867,Allianz Arena,85,Germany,79,François Letexier,78,France,Kasper Hjulmand,Dragan Stojković,255,Kasper Hjulmand,None,1972-04-09,61,Denmark,5908,Dragan Stojković,None,1965-03-03,203,Serbia,1.1.0,2,2
37,3930179,2024-06-24,19:00:00.000,0,1,available,available,2026-05-01T19:46:24.060159,2026-05-01T19:51:26.189211,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,906,Albania,male,None,3,Albania,772,Spain,male,None,214,Spain,10,Group Stage,4866,Merkur Spiel-Arena,85,Germany,1062,Glenn Nyberg,220,Sweden,Sylvio Mendes Campos Junior,Luis de la Fuente Castillo,1877,Sylvio Mendes Campos Junior,Sylvinho,1974-04-12,31,Brazil,5588,Luis de la Fuente Castillo,Luis de la Fuente,1961-06-21,214,Spain,1.1.0,2,2
38,3940983,2024-06-29,19:00:00.000,2,0,available,available,2026-04-28T18:38:21.125369,2026-04-28T18:40:57.190664,4,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,770,Germany,male,None,85,Germany,776,Denmark,male,None,61,Denmark,33,Round of 16,373,Signal-Iduna-Park,85,Germany,1,Michael Oliver,68,England,Julian Nagelsmann,Kasper Hjulmand,445,Julian Nagelsmann,None,1987-07-23,85,Germany,255,Kasper Hjulmand,None,1972-04-09,61,Denmark,1.1.0,2,2
39,3940878,2024-06-29,16:00:00.000,2,0,available,available,2026-04-28T18:37:13.038356,2026-04-28T18:38:32.857625,4,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,773,Switzerland,male,None,221,Switzerland,914,Italy,male,None,112,Italy,33,Round of 16,367,Olympiastadion Berlin,85,Germany,367,Szymon Marciniak,182,Poland,Murat Yakin,Luciano Spalletti,2832,Murat Yakin,None,1974-09-15,221,Switzerland,399,Luciano Spalletti,None,1959-03-07,112,Italy,1.1.0,2,2
40,3930177,2024-06-23,19:00:00.000,0,1,available,available,2026-05-01T19:44:18.003020,2026-05-01T19:47:15.307446,3,55,Europe,UEFA Euro,Europe - UEFA Euro,282,2024,942,Scotland,male,None,201,Scotland,916,Hungary,male,None,103,Hungary,10,Group Stage,369,MHPArena,85,Germany,1094,Facundo Tello Figueroa,11,Argentina,Steve Clarke,Marco Rossi,510,Steve Clarke,None,1963-08-29,201,Scotland,3616,Marco Rossi,None,1964-09-09,112,Italy,1.1.0,2,2

In [6]:
all_lineups = []

for _, match in matches_df.iterrows():

    match_id = match["match_id"]

    lineup_dict = sb.lineups(match_id=match_id)

    team_mapping = {
        match["home_team"]: match["home_team_id"],
        match["away_team"]: match["away_team_id"]
    }

    for team_name, lineup_df in lineup_dict.items():

        lineup_df = lineup_df.copy()

        lineup_df["team_name"] = team_name
        lineup_df["team_id"] = team_mapping.get(team_name)
        lineup_df["match_id"] = match_id

        # Cada posição passa a ser uma linha
        lineup_df = lineup_df.explode("positions")

        # Abrir o dicionário da posição em colunas
        positions_df = pd.json_normalize(lineup_df["positions"])

        positions_df = positions_df.add_prefix("position_")

        # Juntar de volta
        lineup_df = pd.concat(
            [
                lineup_df.drop(columns=["positions"]).reset_index(drop=True),
                positions_df.reset_index(drop=True)
            ],
            axis=1
        )

        #lineup_df = lineup_df.drop(columns=["cards"], errors="ignore")

        all_lineups.append(lineup_df)

lineups_df = pd.concat(all_lineups, ignore_index=True)
lineups_df.to_parquet("../data/raw/lineups.parquet", index=False)
lineups_df

,player_id,player_name,player_nickname,jersey_number,country,cards,team_name,team_id,match_id,position_position_id,position_position,position_from,position_to,position_from_period,position_to_period,position_start_reason,position_end_reason
0,3193,Bernardo Mota Veiga de Carvalho e Silva,Bernardo Silva,10,Portugal,[],Portugal,780,3930166,19.0,Center Attacking Midfield,00:00,89:31,1.0,2.0,Starting XI,Tactical Shift
1,3193,Bernardo Mota Veiga de Carvalho e Silva,Bernardo Silva,10,Portugal,[],Portugal,780,3930166,9.0,Right Defensive Midfield,89:31,None,2.0,NaN,Tactical Shift,Final Whistle
2,5204,Bruno Miguel Borges Fernandes,Bruno Fernandes,8,Portugal,[],Portugal,780,3930166,11.0,Left Defensive Midfield,00:00,None,1.0,NaN,Starting XI,Final Whistle
3,5205,Rui Pedro dos Santos Patrício,Rui Patrício,1,Portugal,[],Portugal,780,3930166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5206,Rúben Santos Gato Alves Dias,Rúben Dias,4,Portugal,[],Portugal,780,3930166,3.0,Right Center Back,00:00,None,1.0,NaN,Starting XI,Final Whistle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3268,22308,Anthony Ralston,None,2,Scotland,"[{'time': '47:19', 'card_type': 'Yellow Card',...",Scotland,942,3930158,7.0,Right Wing Back,00:00,None,1.0,NaN,Starting XI,Final Whistle
3269,22379,Angus Gunn,None,1,Scotland,[],Scotland,942,3930158,1.0,Goalkeeper,00:00,None,1.0,NaN,Starting XI,Final Whistle
3270,31067,Billy Gilmour,None,14,Scotland,[],Scotland,942,3930158,10.0,Center Defensive Midfield,66:26,None,2.0,NaN,Substitution - On (Tactical),Final Whistle
3271,38169,Lawrence Shankland,None,9,Scotland,[],Scotland,942,3930158,23.0,Center Forward,80:54,None,2.0,NaN,Substitution - On (Tactical),Final Whistle
3272,49720,Tommy Conway,None,19,Scotland,[],Scotland,942,3930158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
def get_all_events(match_ids):

    all_events = []

    for match_id in tqdm(match_ids):

        try:
            events_df = sb.events(match_id=match_id)

            # events_df["home_team"] = match["home_team"]
            # events_df["away_team"] = match["away_team"]
            # events_df["competition"] = match.get("competition_name", None)
            # events_df["season"] = match.get("season_name", None)

            all_events.append(events_df)

        except Exception as e:
            print(f"Error loading {match_id}: {e}")

    return pd.concat(all_events, ignore_index=True)


events_df = get_all_events(matches_df["match_id"])
events_df

100%|██████████| 51/51 [00:27<00:00,  1.88it/s]

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,clearance_right_foot,counterpress,dribble_nutmeg,dribble_outcome,duel_outcome,duel_type,duration,foul_committed_advantage,foul_committed_card,foul_committed_offensive,foul_committed_type,foul_won_advantage,foul_won_defensive,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_outcome,goalkeeper_position,goalkeeper_technique,goalkeeper_type,id,index,injury_stoppage_in_chain,interception_outcome,location,match_id,minute,off_camera,out,pass_aerial_won,pass_angle,pass_assisted_shot_id,pass_body_part,pass_cross,pass_cut_back,pass_end_location,pass_goal_assist,pass_height,pass_inswinging,pass_length,pass_miscommunication,pass_no_touch,pass_outcome,pass_outswinging,pass_recipient,pass_recipient_id,pass_shot_assist,pass_straight,pass_switch,pass_technique,pass_through_ball,pass_type,period,play_pattern,player,player_id,position,possession,possession_team,possession_team_id,related_events,second,shot_aerial_won,shot_body_part,shot_end_location,shot_first_time,shot_freeze_frame,shot_key_pass_id,shot_outcome,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure,ball_recovery_offensive,block_deflection,dribble_no_touch,dribble_overrun,miscontrol_aerial_won,shot_deflected,shot_one_on_one,goalkeeper_shot_saved_to_post,shot_saved_to_post,block_offensive,goalkeeper_shot_saved_off_target,shot_saved_off_target,foul_committed_penalty,foul_won_penalty,pass_deflected,shot_redirect,goalkeeper_punched_out,shot_open_goal,block_save_block,goalkeeper_success_in_play,goalkeeper_penalty_saved_to_post,shot_follows_dribble
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9d27853c-ffbc-4011-b7eb-fe3d438e8376,1,NaN,NaN,NaN,3930166,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Portugal,780,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'formation': 3412, 'lineup': [{'player': {'id...",Portugal,780,00:00:00.000,Starting XI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39ad76b2-caaa-41e0-8eb5-f42de9e4e2c6,2,NaN,NaN,NaN,3930166,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Portugal,780,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'formation': 352, 'lineup': [{'player': {'id'...",Czech Republic,912,00:00:00.000,Starting XI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4785617c-2983-4911-a9a6-9edd69fd948b,3,NaN,NaN,NaN,3930166,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Portugal,780,[4046659a-2a5c-496a-93a7-21c139e9fb8f],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portugal,780,00:00:00.000,Half Start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4046659a-2a5c-496a-93a7-21c139e9fb8f,4,NaN,NaN,NaN,3930166,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Portugal,780,[4785617c-2983-4911-a9a6-9edd69fd948b],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Czech Republic,912,00:00:00.000,Half Start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f38b626a-893f-4f74-93d4-a0d87f2534ff,1983,NaN,NaN,NaN,3930166,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,Regular Play,NaN,NaN,NaN,70,Czech Republic,912,[a8664822-bbe2-4a30-b9b5-2ef3154074ff],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portugal,780,00:00:00.000,Half Start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7b43840f-9bb4-4cc6-966b-73942c60f5f7,2912,NaN,NaN,NaN,3930158,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Corner,Toni Kroos,5574.0,Left Defensive Midfield,121,Germany,770,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tactical,103.0,Emre Can,3493.0,NaN,Germany,770,00:35:02.486,Substitution,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8292ddb5-293f-4c2f-806d-87ed439a6cae,2924,NaN,NaN,NaN,3930158,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,Regular Play,Ryan Christie,12510.0,Center Forward,123,Germany,770,NaN,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tactical,103.0,Lawrence Shankland,38169.0,NaN,Scotland,942,00:35:54.594,Substitution,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6adeb4a7-3b03-4fe0-9dda-c00748dcfe42,2557,NaN,NaN,"[15.1, 46.4]",3930158,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Throw In,Grant Campbell Hanley,9481.0,Center Back,107,Germany,770,NaN,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scotland,942,00:22:41.537,Error,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a291aa7d-39b0-4d7a-86f2-8be1171b7caf,3099,NaN,NaN,"[109.8, 47.3]",3930158,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Free Kick,NaN,NaN,NaN,132,Scotland,942,[0dd8fd49-5fea-4710-84fc-6e06fb83e757],32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scotland,942,00:41:32.702,Own Goal For,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,NaN,NaN,"[10.3, 32.8]",3930158,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Germany,770,00:41:32.702,Own Goal Against,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
def get_all_frames(match_ids):

    all_frames = []

    for match_id in tqdm(match_ids):

        try:
            frames_df = sb.frames(match_id=match_id)

            all_frames.append(frames_df)

        except Exception as e:
            print(f"Error loading {match_id}: {e}")

    return pd.concat(all_frames, ignore_index=True)

events_360_df = get_all_frames(matches_df["match_id"])

100%|██████████| 51/51 [00:48<00:00,  1.06it/s]

In [9]:
events_360_df

,id,visible_area,match_id,teammate,actor,keeper,location
0,87a790b7-17a6-4bbd-953f-a06c07edbad9,"[18.400697860849267, 80.0, 46.48865423106284, ...",3930166,True,False,False,"[38.20338261131079, 29.491675823953365]"
1,87a790b7-17a6-4bbd-953f-a06c07edbad9,"[18.400697860849267, 80.0, 46.48865423106284, ...",3930166,True,False,False,"[40.435487610014256, 49.496164383322295]"
2,87a790b7-17a6-4bbd-953f-a06c07edbad9,"[18.400697860849267, 80.0, 46.48865423106284, ...",3930166,True,False,False,"[51.887832712562904, 56.43639891583137]"
3,87a790b7-17a6-4bbd-953f-a06c07edbad9,"[18.400697860849267, 80.0, 46.48865423106284, ...",3930166,True,False,False,"[60.036085232306185, 31.006609171941484]"
4,87a790b7-17a6-4bbd-953f-a06c07edbad9,"[18.400697860849267, 80.0, 46.48865423106284, ...",3930166,True,False,False,"[60.838859912993875, 4.272189145609488]"
...,...,...,...,...,...,...,...
2698994,5ce3666b-f6c5-4426-a16c-7928236bbdac,"[0.0, 80.0, 0.0, 28.23202227625909, 22.9743547...",3930158,True,False,False,"[15.948856551775805, 55.95216286228902]"
2698995,5ce3666b-f6c5-4426-a16c-7928236bbdac,"[0.0, 80.0, 0.0, 28.23202227625909, 22.9743547...",3930158,False,False,False,"[17.452580090224245, 33.005712133560706]"
2698996,5ce3666b-f6c5-4426-a16c-7928236bbdac,"[0.0, 80.0, 0.0, 28.23202227625909, 22.9743547...",3930158,False,False,False,"[19.947396309933282, 45.41233704070139]"
2698997,5ce3666b-f6c5-4426-a16c-7928236bbdac,"[0.0, 80.0, 0.0, 28.23202227625909, 22.9743547...",3930158,True,False,False,"[20.328016357383106, 42.49520526434236]"
2698998,5ce3666b-f6c5-4426-a16c-7928236bbdac,"[0.0, 80.0, 0.0, 28.23202227625909, 22.9743547...",3930158,False,False,False,"[27.303963268629587, 37.671268480704946]"

In [10]:
# Realizamos o merge dos eventos com os dados 360º através do id do evento
events_df = events_df.merge(events_360_df, on="id", how="left")
events_df.to_parquet("../data/raw/events.parquet", index=False)
events_df

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,clearance_right_foot,counterpress,dribble_nutmeg,dribble_outcome,duel_outcome,duel_type,duration,foul_committed_advantage,foul_committed_card,foul_committed_offensive,foul_committed_type,foul_won_advantage,foul_won_defensive,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_outcome,goalkeeper_position,goalkeeper_technique,goalkeeper_type,id,index,injury_stoppage_in_chain,interception_outcome,location_x,match_id_x,minute,off_camera,out,pass_aerial_won,pass_angle,pass_assisted_shot_id,pass_body_part,pass_cross,pass_cut_back,pass_end_location,pass_goal_assist,pass_height,pass_inswinging,pass_length,pass_miscommunication,pass_no_touch,pass_outcome,pass_outswinging,pass_recipient,pass_recipient_id,pass_shot_assist,pass_straight,pass_switch,pass_technique,pass_through_ball,pass_type,period,play_pattern,player,player_id,position,possession,possession_team,possession_team_id,related_events,second,shot_aerial_won,shot_body_part,shot_end_location,shot_first_time,shot_freeze_frame,shot_key_pass_id,shot_outcome,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure,ball_recovery_offensive,block_deflection,dribble_no_touch,dribble_overrun,miscontrol_aerial_won,shot_deflected,shot_one_on_one,goalkeeper_shot_saved_to_post,shot_saved_to_post,block_offensive,goalkeeper_shot_saved_off_target,shot_saved_off_target,foul_committed_penalty,foul_won_penalty,pass_deflected,shot_redirect,goalkeeper_punched_out,shot_open_goal,block_save_block,goalkeeper_success_in_play,goalkeeper_penalty_saved_to_post,shot_follows_dribble,visible_area,match_id_y,teammate,actor,keeper,location_y
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9d27853c-ffbc-4011-b7eb-fe3d438e8376,1,NaN,NaN,NaN,3930166,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Portugal,780,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'formation': 3412, 'lineup': [{'player': {'id...",Portugal,780,00:00:00.000,Starting XI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39ad76b2-caaa-41e0-8eb5-f42de9e4e2c6,2,NaN,NaN,NaN,3930166,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Portugal,780,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'formation': 352, 'lineup': [{'player': {'id'...",Czech Republic,912,00:00:00.000,Starting XI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4785617c-2983-4911-a9a6-9edd69fd948b,3,NaN,NaN,NaN,3930166,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Portugal,780,[4046659a-2a5c-496a-93a7-21c139e9fb8f],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portugal,780,00:00:00.000,Half Start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4046659a-2a5c-496a-93a7-21c139e9fb8f,4,NaN,NaN,NaN,3930166,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Portugal,780,[4785617c-2983-4911-a9a6-9edd69fd948b],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Czech Republic,912,00:00:00.000,Half Start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f38b626a-893f-4f74-93d4-a0d87f2534ff,1983,NaN,NaN,NaN,3930166,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,Regular Play,NaN,NaN,NaN,70,Czech Republic,912,[a8664822-bbe2-4a30-b9b5-2ef3154074ff],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portugal,780,00:00:00.000,Half Start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2722388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,NaN,NaN,"[10.3, 32.8]",3930158,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Germany,770,00:41:32.702,Own Goal Against,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[29.752411154964918, 79.22086739213373, 0.0, 4...",3930158.0,False,False,False,"[17.191577570485677, 42.22972347817744]"
2722389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,NaN,NaN,"[10.3, 32.8]",3930158,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Germany,770,00:41:32.702,Own Goal Against,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[29.752411154964918, 79.22086739213373, 0.0, 4...",3930158.0,True,False,False,"[17.965696465999017, 29.694118095738418]"
2722390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,NaN,NaN,"[10.3, 32.8]",3930158,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Germany,770,00:41:32.702,Own Goal Against,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[29.752411154964918, 79.22086739213373, 0.0, 4...",3930158.0,True,False,False,"[25.70225726023301, 36.307377809078865]"
2722391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,NaN,NaN,"[10.3, 32.8]",3930158,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Germany,770,00:41:32.702,Own Goal Against,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[29.752411154964918, 79.22086739213373, 0.0, 4...",3930158.0,False,False,False,"[30.580730722937282, 47.8590938785301]"
2722392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,NaN,NaN,"[10.3, 32.8]",3930158,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Germany,770,00:41:32.702,Own Goal Against,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[29.752411154964918, 79.22086739213373, 0.0, 4...",3930158.0,True,False,False,"[37.21744231751122, 59.8941166423611]"